{% set version = "2.3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set sha256 = "d753d42b42ff28c1cd25c63916fb2aa9e325941672fb16f7dfd97e218416cf2a" %}

package:
  name: r-envstats
  version: {{ version|replace("-", "_") }}

source:
  fn: EnvStats_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/EnvStats_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/EnvStats/EnvStats_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-ggplot2
    - r-nortest

  run:
    - r-base
    - r-mass
    - r-ggplot2
    - r-nortest

test:
  commands:
    - $R -e "library('EnvStats')"  # [not win]
    - "\"%R%\" -e \"library('EnvStats')\""  # [win]

about:
  home: https://www.probstatinfo.com
  license: GPL (>= 3)
  summary: >
    Graphical and statistical analyses of environmental data, with  focus on analyzing
    chemical concentrations and physical parameters, usually in  the context of mandated
    environmental monitoring.  Major environmental  statistical methods found in the
    literature and regulatory guidance documents,  with extensive help that explains
    what these methods do, how to use them,  and where to find them in the literature.  Numerous
    built-in data sets from  regulatory guidance documents and environmental statistics
    literature.  Includes  scripts reproducing analyses presented in the book "EnvStats: An R Package for 
    Environmental Statistics" (Millard, 2013, Springer, ISBN 978-1-4614-8455-4, 
    <http://www.springer.com/book/9781461484554>).
  license_family: GPL3

extra:
  recipe-maintainers:
    - jentjr
