{% set version = "2.7.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set sha256 = "09a6f0d5b60856c7298371e4a8a085a1db7abf0e71ccb9a2dc9ca24248fb5d81" %}

package:
  name: r-envstats
  version: {{ version|replace("-", "_") }}

source:
  fn: EnvStats_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/EnvStats_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/EnvStats/EnvStats_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-ggplot2
    - r-nortest

  run:
    - r-base
    - r-mass
    - r-ggplot2
    - r-nortest

test:
  commands:
    - $R -e "library('EnvStats')"  # [not win]
    - "\"%R%\" -e \"library('EnvStats')\""  # [win]

about:
  home: https://www.probstatinfo.com
  license: GPL-3.0-or-later
  summary: >
    Graphical and statistical analyses of environmental data, with  focus on analyzing chemical concentrations and physical parameters, usually in  the context of mandated environmental monitoring.  Major environmental  statistical methods found in the literature and regulatory guidance documents,  with extensive help that
    explains what these methods do, how to use them,  and where to find them in the literature.  Numerous built-in data sets from  regulatory guidance documents and environmental statistics literature.  Includes  scripts reproducing analyses presented in the book "EnvStats: An R Package for  Environmental Statistics" (Millard,
    2013, Springer, ISBN 978-1-4614-8455-4,  <http://www.springer.com/book/9781461484554>).
  license_family: GPL3

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - jentjr
