# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DsB/5HyAMg85ajWr5KfYkmR3yDiMXyz+0RI5UX3KEt6hz9LMLU6FP1WAz/iY8jQHh0Ees/V3ysLW28eYCkHQ7B2DZ1xKabajw5YFYa+Gu5dohEQh5qLBmfBHjRp+Rqv0sd/UdgY2oK6+/wDIBAxdcLBhNcRzNk9+a7FSWn/ZGbf8WI8W/V3QEErP3dYr2hErj3PKoaACtDmyq20aIdGov5MFWbkFGExp0zAafeW95QXvIlaBKnyg6cUqCoW1wbxoP1ch6q3lC5V8YNESS9qvUJymImymrHLz2lWYFyZ7CO5NWnUz25blokXt5SjwiLFf7RIp4a8RWbVSjjajrkfulC55sEOiMbhwKpexBvM9xFflBw1RM2SNOOOfmQcppKKntXgWMmFye9E8SLaPP3DKNslxJisylKGQPtBrelcCwZ2gNDRp3PndKsc7CaaK+W//ju+V2EaQvvyKKMt4kOOig3JLnEItso/q/1Bnmk3OlJTmq9p3pKBk7pEWM638G2MKJ/dJroaDu7iVfY+KyW1oHtOkEMCmYu2EdVjOu/wwsYnSFiCiFh7h7UiAzUap68kNayux4lLsCr2BPn7gVCuT/vSbuH7TfyKptP5pjbCB9pprO9ptston945jZafXVogTY9zBJil2/nJvYCxhgMtRaHDWIAYq4V8SwgDpR3dcGtA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
