travis:
  secure:
    BINSTAR_TOKEN: PNg1+yyIqxX6GZhW/tunGEHRA+y43AQSu2qdKUOzJ506MIzzom+kDtOUYZcyRCKyFRxDpUpX8ukSCURzKUiT+VLNdCUb6/0AS6Re5Zkawx2yrpTsuv7iLqwaFp36KopZsPbK3WK2rbhvY2WEnSkt6mQSWQm23rad/0RnagVAFnNRI8kyxOpoOXLf73Kw3f0QbVtDYt+jK3qnuGkeK9ZRAu3CeMrLiRMgi0mKv0DdMLK6iW/OxxV0gYaLVSOpqji2Qi+ar+6opoHvQblZt17GbDP6FhmW4+NLTFPXSEy9/Y3TOIEisd7vwFeX34aKgrj0XBRkoxFUwXaoOGLPAc4oRGQnJdQyfb8Yt0JJOyhP3Oitc1Jm5zpkcGD3teussxVkQ6hXVcO+qcvdgmWpjQQX5rmd1J1SY5VxbMggp+W1Q9Yynbj3/b8il4V4rnKIP0/MrGHkiyZRVS5iWW22S1rnpOwhfgbqUaFo+sjYkpoYazr/E3E9/fs83uxX4omKttgp+aXpzY15xdavtO1OONzajqeugbmjhZl7w6AUM5hDY6WyrfdnoD7KTf4MyOeD0aVnNLZsgHCO3hwD+gvG4f/suCxiDsfFJWsuY9MVpOK5JJXz23POHxjXPXM30o+/nOEYI38qK5wOpUw++JOV6xdAIFs0WOU4DwbvSK09vhMybRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
